### ISSUE TITLE
[object PositionError]

### ISSUE THREAD

**Issue by rubenspgcavalcante** [rubenspgcavalcante/findabike#2]
https://sentry.io/rubens-pinheiro/find-a-bike/issues/493725971/

```
Stacktrace (most recent call first):

  at this (./modules/commons/epics/index.js:90:11)
  at [4]/N</< (./modules/commons/epics/index.js:73:16)

[object PositionError]
```

**Comment by rubenspgcavalcante** [comment]
Check for Position Error and do a proper feedback to the user
